// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as App$Dojo from "./App.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$Dojo.make(/* array */[])), "root");

var match = module.hot;

if (match == null) {
  console.log("We are not hot");
} else {
  match.accept();
}

export {
  
}
/*  Not a pure module */
