// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as YoloJs from "./yolo.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function make(text, children) {
  return ReasonReact.wrapJsForReason(YoloJs.default, {
              text: text
            }, children);
}

export {
  make ,
  
}
/* ./yolo.js Not a pure module */
